### ISSUE TITLE
ValueError: Only one of 'nopython' or 'forceobj' can be True

### ISSUE THREAD

**Issue by jonnew** [lambdaloop/anipose#37] opened 2020-08-19 23:32 UTC
**Describe the bug**
```
(anipose) hand-demo-unfilled[0]$ anipose analyze
Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/anipose/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/anipose/anipose.py", line 135, in analyze
    from .pose_videos import pose_videos_all
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/anipose/pose_videos.py", line 11, in <module>
    from .common import natural_keys, make_process_fun
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/anipose/common.py", line 10, in <module>
    from aniposelib.boards import CharucoBoard, Checkerboard
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/aniposelib/__init__.py", line 6, in <module>
    from . import boards, cameras, utils
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/aniposelib/cameras.py", line 428, in <module>
    class CameraGroup:
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/aniposelib/cameras.py", line 616, in CameraGroup
    @jit(nopython=True, parallel=True, forceobj=True)
  File "/home/jon/anaconda3/envs/anipose/lib/python3.7/site-packages/numba/core/decorators.py", line 147, in jit
    raise ValueError("Only one of 'nopython' or 'forceobj' can be True.")
ValueError: Only one of 'nopython' or 'forceobj' can be True.
(anipose) hand-demo-unfilled[0]$ 
```

Seems Related: https://gitter.im/numba/numba?at=5eafceefb6dd230697a45990

**To Reproduce**
Install via instructions on docs website
Download the hand-demo-unfilled data set 
Call `anipose analyze` on the hand-demo-unfilled data set 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by lambdaloop** [comment] 2020-09-28 15:34
I'm closing this as a duplicate of issue #38

**Closed by lambdaloop** 2020-09-28 15:34 UTC
