### ISSUE TITLE
error during calibration

### ISSUE THREAD

**Issue by cgutierrez-Ibanez** [lambdaloop/anipose#7] opened 2019-12-04 20:25 UTC
Hi,

Using windows 10, installed anipose today from "pip install anipose" 
While trying to use anipose calibrate I get this error, 

(dlc-windowsGPU) C:\deeplabcut\anipose3d recon>anipose calibrate
Calibrating...
C:\deeplabcut\anipose3d recon\session1\calibration\calibration.toml
C:\deeplabcut\anipose3d recon\session1\calibration\cam1cut.avi
100%|█████████████████████████████| 1056/1056 [00:19<00:00, 53.65it/s]
1056 boards detected
C:\deeplabcut\anipose3d recon\session1\calibration\cam2cut.avi
100%|█████████████████████████████| 1056/1056 [00:21<00:00, 50.00it/s]
1056 boards detected
defaultdict(<class 'int'>, {})
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Anaconda3\envs\dlc-windowsGPU\Scripts\anipose.exe\__main__.py", line 9, in <module>
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\anipose.py", line 109, in calibrate
    calibrate_all(config)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\anipose\calibrate.py", line 184, in process_session
    n_samp_iter=100, n_samp_full=2000)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\calligator\cameras.py", line 1555, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\calligator\utils.py", line 174, in get_initial_extrinsics
    extrinsics = compute_camera_matrices(rtvecs, pairs)
  File "c:\users\user\anaconda3\envs\dlc-windowsgpu\lib\site-packages\calligator\utils.py", line 164, in compute_camera_matrices
    source = pairs[0][0]
IndexError: list index out of range

a pickle file is created. 
Thank you. 

cristian

**Comment by lambdaloop** [comment] 2019-12-05 00:57
Hi @cgutierrez-Ibanez ,

Thank you for filing this issue. 
It seems to not be finding any detected checkerboards pairs, which is odd since it seems that checkerboards are detected in all frames.

I need to reproduce this bug to diagnose it further. 

Could you share:
- your config.toml file
- the pickle file that is generated
- the calibration videos used

Thank you!

**Comment by oilbird** [comment] 2019-12-05 01:07
Thank you for the reply, attached is the two videos, toml file and the generated pickle. 
[califilesgutanipo.zip](https://github.com/lambdaloop/anipose/files/3924624/califilesgutanipo.zip)

**Comment by cgutierrez-Ibanez** [comment] 2019-12-05 01:10
I just realized  i log in with a different account. same person.

**Comment by lambdaloop** [comment] 2019-12-05 06:06
Hi @cgutierrez-Ibanez ,

I was able to reproduce the issue. 

It turns out that you had misspecified your camera regex pattern, so that it was not matching your files appropriately. In particular, your cam_regex variable was set to:
`cam_regex = 'cam([1-9])$'`
which translates to 'cam' followed by a digit 1-9 (which is the name of the camera), followed by the end of the filename.

However, your calibration video files are named cam1cut.avi and cam2cut.avi , so the "cam1" and "cam2"  parts are not at the end of the name. To fix this, simply update the cam_regex to:
`cam_regex = 'cam([1-9])'`

You will need to delete your detections.pickle file to reprocess properly.
After changing cam_regex and deleting the pickle file, I was able to obtain a good calibration.

Let me know if that works.

**Comment by lambdaloop** [comment] 2019-12-05 06:07
To mitigate this issue for future users, I will update Anipose to throw an error/warning when the camera regex name does not match the files to highlight this issue better.

**Comment by lambdaloop** [comment] 2019-12-11 19:53
Hi @cgutierrez-Ibanez ,

Did you end up trying out the fix? Did it work for you?

Let me know

**Comment by cgutierrez-Ibanez** [comment] 2019-12-11 20:34
Hi, 

Sorry, it has been a busy week. Yes, it works! thank you. It now creates a full calibration, but then when trying to analyze videos, it seems to start deeplabcut, but then nothing happens.  I believe the naming is correct. I named the cameras cam1 and cam 2 and the video files are named xxxcam1.avi and xxxcam2.avi, I tried cam_regex = 'cam([1-9])$' and cam_regex = 'cam([1-9])' but in both cases is the same.  I have a main anipose3d folder in which there is a session1folder, and in there two subfolders, one called calibration and the other videos-raw. Is probably some naming problem or something  I am missing on the tom file. or maybe the path to the deeplabcut folder?

**Comment by lambdaloop** [comment] 2019-12-11 21:08
Ah, I think for your folder structure, you should set `nesting = 1` in your config.toml.

**Comment by cgutierrez-Ibanez** [comment] 2019-12-12 17:13
sorry about that. Now is (mostly) working. I can get 3d poses, which look very similar to what I got using the deeplabcut triangulation.  The one problem is that using filter-3d gives me almost completely blank  .csv files.  

also, while I have your attention,  in the 3d pose files, is the data in mm? Thank you for all the help, patience and great work.

**Comment by lambdaloop** [comment] 2019-12-13 03:25
Yes, if you've got missing data, the 3D median filter probably will not work that well. In any case, there is now a better filter available, which smooths the data and can constrain the length of certain joint pairs. It will also interpolate the missing data.

Here's an example configuration for constrained optimization:
```toml
[triangulation]
optim = true
constraints = [
    ['right_middle_knuckle', 'right_wrist'], ['left_middle_knuckle', 'left_wrist'] # set of constant limb length constraints written out as pairs
]
scale_smooth = 2 # strength of smoothness constraint, higher gives smoother trajectory
scale_length = 2 # strength of length constraint, higher enforces less variability in limb lengths
reproj_error_threshold = 5 # in pixels, for robust triangulation
score_threshold = 0.3 # score threshold for triangulation
n_deriv_smooth = 2 # derivative to minimize for smoothness
```

**Comment by lambdaloop** [comment] 2020-02-21 02:12
I think the original issue is resolved, so I am closing this issue.

**Closed by lambdaloop** 2020-02-21 02:12 UTC
