### ISSUE TITLE
calibration_init.toml not found?

### ISSUE THREAD

**Issue by elhananby** [lambdaloop/anipose#1] opened 2019-08-27 11:17 UTC
Hi, I'm trying to setup anipose for tracking, and I run into an issue when using "anipose calibrate" - it can't find the calibration_init.toml file. I could not find an example of such a file in the repository, what is it's exact role?

Thanks

**Comment by lambdaloop** [comment] 2019-08-28 21:51
Hello! Thank you for filing this issue. 

I'm guessing you have a line in your `config.toml` file which looks like 
```toml
[calibration]
calibration_init = 'calibration_init.toml'
```

This is (currently) an undocumented feature which allows you to specify initial parameters for the calibration if you have a guess. It's not needed and you should be able to remove the line to use the automated parameter initialization.

**Comment by lambdaloop** [comment] 2019-10-22 06:51
Hi @elhananby ,

Have you resolved this issue?

**Comment by elhananby** [comment] 2019-10-29 14:31
Hi Pierre, sorry for the very late response!
I took a small break from the specific project but recently tried to re-run it. I followed your advice and removed the line, however the current error I'm getting after running anipose --config (my config filename) calibrate is:
```
/home/elhanan_la/Videos/experiment/session1/calibration/calibration.toml
/home/elhanan_la/Videos/experiment/session1/calibration/cam0_calibrate_191029_151437.mp4
43 boards detected
/home/elhanan_la/Videos/experiment/session1/calibration/cam1_calibrate_191029_151437.mp4
61 boards detected
/home/elhanan_la/Videos/experiment/session1/calibration/cam2_calibrate_191029_151437.mp4
95 boards detected
defaultdict(<class 'int'>, {})
Traceback (most recent call last):
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/bin/anipose", line 8, in <module>
    sys.exit(cli())
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/anipose/anipose.py", line 108, in calibrate
    calibrate_all(config)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/anipose/common.py", line 168, in fun
    return process_all(config, process_session, **args)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/anipose/common.py", line 153, in process_all
    output[past_folders] = process_session(config, path, **args)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/anipose/calibrate.py", line 183, in process_session
    n_samp_iter=100, n_samp_full=2000)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/calligator/cameras.py", line 1555, in calibrate_rows
    rvecs, tvecs = get_initial_extrinsics(rtvecs)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/calligator/utils.py", line 174, in get_initial_extrinsics
    extrinsics = compute_camera_matrices(rtvecs, pairs)
  File "/home/elhanan_la/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/calligator/utils.py", line 164, in compute_camera_matrices
    source = pairs[0][0]
IndexError: list index out of range
```
From manually running the same videos through OpenCV board detection algorithms I know there are multiple frames where the boards are detected on at least two cameras, so I don't think it's an issue with lack of overlapping frames.

Best,
Elhanan

**Comment by lambdaloop** [comment] 2019-10-30 21:30
Huh, that's strange. Could you share your calibration videos and config.toml file so I could reproduce the error?

**Comment by lambdaloop** [comment] 2019-11-03 22:55
Looking over the error again, you seem to have very few boards detected, and it's possible there is no overlap between two cameras in those detections. Could it be that you mispecified your calibration board parameters?

**Comment by elhananby** [comment] 2019-11-08 16:22
I've ran it again on a longer video and got around 300 detections for each camera, and I still get the same error.
I have attached the calibration videos and my config file (which is mostly the default file, i'm just trying to get the calibration working now) via Google drive:
[https://drive.google.com/drive/folders/1lfZFQfoNs-mEefIr1B0XiZD76Y2VmrG4?usp=sharing](url)

**Comment by lambdaloop** [comment] 2019-11-08 18:39
That's great! I'm glad you got it to work! 
I will close this issue then.

Feel free to open another issue if you get another problem!

**Closed by lambdaloop** 2019-11-08 18:39 UTC
